using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RailwayTicketingProject
{
    public class Stations
    {
        public List<StationList> AllStation = new List<StationList>
        {
  new StationList(){StationCode= "ABN", StationID= 3, StationName= "ABANPOLA"},
  new StationList(){StationCode= "ADAGALA", StationID= 410, StationName= "ADAGALA"},
  new StationList(){StationCode= "ANM", StationID= 11, StationName= "AHANGAMA"},
  new StationList(){StationCode= "AUH", StationID= 18, StationName= "AHUNGALLE"},
  new StationList(){StationCode= "APR", StationID= 13, StationName= "AKBOPURA"},
  new StationList(){StationCode= "AKU", StationID= 7, StationName= "AKURALA"},
  new StationList(){StationCode= "AWP", StationID= 22, StationName= "ALAWATUPITIYA"},
  new StationList(){StationCode= "ALW", StationID= 9, StationName= "ALAWWA"},
  new StationList(){StationCode= "ATB", StationID= 329, StationName= "ALUTH AMBALAMA"},
  new StationList(){StationCode= "ALT", StationID= 8, StationName= "ALUTHGAMA"},
  new StationList(){StationCode= "ABA", StationID= 1, StationName= "AMBALANGODA"},
  new StationList(){StationCode= "ABL", StationID= 2, StationName= "AMBEWELA"},
  new StationList(){StationCode= "APS", StationID= 14, StationName= "AMBEYPUSSA"},
  new StationList(){StationCode= "AVD", StationID= 19, StationName= "ANAWILUNDAWA"},
  new StationList(){StationCode= "AND", StationID= 10, StationName= "ANDADOLA"},
  new StationList(){StationCode= "AGT", StationID= 5, StationName= "ANGAMPITIYA"},
  new StationList(){StationCode= "AGL", StationID= 4, StationName= "ANGULANA"},
  new StationList(){StationCode= "ANP", StationID= 12, StationName= "ANURADHAPURA"},
  new StationList(){
      StationCode= "APT", StationID= 15, StationName= "ANURADHAPURA TOWN"},
  new StationList(){
      StationCode= "AKT", StationID= 6, StationName= "ARACHCHIKATTUWA"},
  new StationList(){StationCode= "ARP", StationID= 343, StationName= "ARAPATHGAMA"},
  new StationList(){StationCode= "ARW", StationID= 16, StationName= "ARUKKUWATTE"},
  new StationList(){StationCode= "ASL", StationID= 17, StationName= "ASELAPURA"},
  new StationList(){StationCode= "AGR", StationID= 467, StationName= "ASGIRIYA"},
  new StationList(){StationCode= "AWK", StationID= 21, StationName= "AUKANA"},
  new StationList(){StationCode= "AVS", StationID= 20, StationName= "AVISSAWELLA"},
  new StationList(){StationCode= "BAD", StationID= 23, StationName= "BADULLA"},
  new StationList(){StationCode= "BNA", StationID= 31, StationName= "BALANA"},
  new StationList(){StationCode= "BPA", StationID= 34, StationName= "BALAPITIYA"},
  new StationList(){StationCode= "BPT", StationID= 35, StationName= "BAMBALAPITIYA"},
  new StationList(){StationCode= "BDA", StationID= 25, StationName= "BANDARAWELA"},
  new StationList(){
      StationCode= "Bandirippuwa", StationID= 475, StationName= "Bandirippuwa"},
  new StationList(){StationCode= "BGY", StationID= 28, StationName= "BANGADENIYA"},
  new StationList(){StationCode= "BSL", StationID= 39, StationName= "BASELINE ROAD"},
  new StationList(){StationCode= "BOA", StationID= 33, StationName= "BATTALUOYA"},
  new StationList(){StationCode= "BCO", StationID= 24, StationName= "BATTICALOA"},
  new StationList(){StationCode= "BTU", StationID= 41, StationName= "BATUWATTE"},
  new StationList(){StationCode= "BEM", StationID= 26, StationName= "BEMMULLA"},
  new StationList(){StationCode= "BNT", StationID= 32, StationName= "BENTOTA"},
  new StationList(){StationCode= "BRL", StationID= 36, StationName= "BERUWALA"},
  new StationList(){StationCode= "BLT", StationID= 30, StationName= "BOLAWATTE"},
  new StationList(){StationCode= "BSH", StationID= 38, StationName= "BOOSSA"},
  new StationList(){StationCode= "BSA", StationID= 37, StationName= "BORELESSA"},
  new StationList(){StationCode= "BTL", StationID= 40, StationName= "BOTALE"},
  new StationList(){StationCode= "BGH", StationID= 27, StationName= "BULUGAHAGODA"},
  new StationList(){StationCode= "BJM", StationID= 29, StationName= "BUTHGAMUWA"},
  new StationList(){
      StationCode= "CCH", StationID= 398, StationName= "CHAVAKACHCHERI"},
  new StationList(){StationCode= "CDK", StationID= 371, StationName= "CHEDDIIKULAM"},
  new StationList(){StationCode= "CHL", StationID= 44, StationName= "CHILAW"},
  new StationList(){StationCode= "CBY", StationID= 43, StationName= "CHINA BEY"},
  new StationList(){StationCode= "CKM", StationID= 423, StationName= "CHUNNAKAM"},
  new StationList(){StationCode= "FOT", StationID= 61, StationName= "COLOMBO FORT"},
  new StationList(){StationCode= "CRD", StationID= 46, StationName= "COTTA ROAD"},
  new StationList(){StationCode= "DRL", StationID= 53, StationName= "DARALUWA"},
  new StationList(){StationCode= "DEC", StationID= 457, StationName= "DEC"},
  new StationList(){StationCode= "DWL", StationID= 54, StationName= "DEHIWALA"},
  new StationList(){StationCode= "DKD", StationID= 337, StationName= "Dekinda"},
  new StationList(){StationCode= "DAG", StationID= 47, StationName= "DEMATAGODA"},
  new StationList(){StationCode= "DDR", StationID= 48, StationName= "DEMODARA"},
  new StationList(){StationCode= "DPM", StationID= 52, StationName= "DEWAPURAM"},
  new StationList(){StationCode= "DEWEDDA", StationID= 417, StationName= "DEWEDDA"},
  new StationList(){StationCode= "DLA", StationID= 50, StationName= "DIYATALAWA"},
  new StationList(){StationCode= "DNA", StationID= 51, StationName= "DODANDUWA"},
  new StationList(){StationCode= "EYA", StationID= 60, StationName= "EGODA UYANA"},
  new StationList(){
      StationCode= "EPS", StationID= 395, StationName= "ELIPHANT PASS"},
  new StationList(){StationCode= "ELL", StationID= 57, StationName= "ELLE"},
  new StationList(){
      StationCode= "EML", StationID= 401, StationName= "ELUTHUMATTUVAL"},
  new StationList(){StationCode= "ELW", StationID= 341, StationName= "ELWALA"},
  new StationList(){StationCode= "EDM", StationID= 55, StationName= "ENDERAMULLA"},
  new StationList(){
      StationCode= "EKM", StationID= 56, StationName= "ERATTAPERIYAKULAM"},
  new StationList(){StationCode= "EVR", StationID= 59, StationName= "ERAVUR"},
  new StationList(){
      StationCode= "EPN", StationID= 58, StationName= "ERUKKALAM PENDU"},
  new StationList(){
      StationCode= "IPZ", StationID= 104, StationName= "FREE TRADE ZONE"},
  new StationList(){StationCode= "GBD", StationID= 64, StationName= "GALABODA"},
  new StationList(){StationCode= "GLM", StationID= 69, StationName= "GALGAMUWA"},
  new StationList(){StationCode= "GLE", StationID= 68, StationName= "GALLE"},
  new StationList(){StationCode= "GAL", StationID= 62, StationName= "GALLELLA"},
  new StationList(){
      StationCode= "GOA", StationID= 74, StationName= "GALOYA JUNCTION"},
  new StationList(){StationCode= "GMA", StationID= 70, StationName= "GAMMANA"},
  new StationList(){StationCode= "GPH", StationID= 75, StationName= "GAMPAHA"},
  new StationList(){StationCode= "GPL", StationID= 76, StationName= "GAMPOLA"},
  new StationList(){StationCode= "GND", StationID= 71, StationName= "GANEGODA"},
  new StationList(){StationCode= "GAN", StationID= 63, StationName= "GANEMULLA"},
  new StationList(){StationCode= "GNW", StationID= 73, StationName= "GANEWATTE"},
  new StationList(){
      StationCode= "Gangathilaka", StationID= 479, StationName= "Gangathilaka"},
  new StationList(){StationCode= "GDA", StationID= 65, StationName= "GANGODA"},
  new StationList(){StationCode= "GTL", StationID= 440, StationName= "GANTALAWA"},
  new StationList(){StationCode= "GEY", StationID= 66, StationName= "GELIOYA"},
  new StationList(){StationCode= "GNT", StationID= 72, StationName= "GINTHOTA"},
  new StationList(){StationCode= "GRB", StationID= 476, StationName= "GIRAMBE"},
  new StationList(){StationCode= "GRB", StationID= 77, StationName= "GIRAMBE"},
  new StationList(){StationCode= "GGA", StationID= 67, StationName= "GODAGAMA"},
  new StationList(){StationCode= "GWN", StationID= 79, StationName= "GREAT WESTERN"},
  new StationList(){StationCode= "HBD", StationID= 81, StationName= "HABARADUWA"},
  new StationList(){StationCode= "HBN", StationID= 82, StationName= "HABARANA"},
  new StationList(){
      StationCode= "HADIRIWALANA", StationID= 456, StationName= "Hadiriwalana"},
  new StationList(){StationCode= "HEA", StationID= 84, StationName= "HALIELA"},
  new StationList(){StationCode= "HPT", StationID= 92, StationName= "HAPUTALE"},
  new StationList(){StationCode= "HAU", StationID= 80, StationName= "HATAMUNA"},
  new StationList(){
      StationCode= "HKT", StationID= 87, StationName= "HATARAS KOTUWA"},
  new StationList(){StationCode= "HTN", StationID= 96, StationName= "HATTON"},
  new StationList(){StationCode= "HLO", StationID= 89, StationName= "HEEL OYA"},
  new StationList(){StationCode= "HDP", StationID= 83, StationName= "HEENDENIYA"},
  new StationList(){StationCode= "HML", StationID= 91, StationName= "HETTIMULLA"},
  new StationList(){StationCode= "HKD", StationID= 86, StationName= "HIKKADUWA"},
  new StationList(){StationCode= "HRG", StationID= 93, StationName= "HINGURAKGODA"},
  new StationList(){
      StationCode= "Hingurala", StationID= 444, StationName= "HINGURALA"},
  new StationList(){StationCode= "HRL", StationID= 94, StationName= "HIRIYALA"},
  new StationList(){StationCode= "HMA", StationID= 90, StationName= "HOMAGAMA"},
  new StationList(){
      StationCode= "HHR", StationID= 85, StationName= "HOMAGAMA HOSPITAL"},
  new StationList(){StationCode= "HRP", StationID= 95, StationName= "HORAPE"},
  new StationList(){StationCode= "HLA", StationID= 88, StationName= "HORIWIALA"},
  new StationList(){StationCode= "HUN", StationID= 97, StationName= "HUNUPITIYA"},
  new StationList(){StationCode= "HYP", StationID= 98, StationName= "HYINPORT"},
  new StationList(){StationCode= "IGH", StationID= 100, StationName= "IDALGASINNA"},
  new StationList(){StationCode= "IHA", StationID= 101, StationName= "IHALAGAMA"},
  new StationList(){StationCode= "IKT", StationID= 102, StationName= "IHALAKOTTE"},
  new StationList(){
      StationCode= "IWL", StationID= 105, StationName= "IHALAWATAWALA"},
  new StationList(){StationCode= "IDA", StationID= 99, StationName= "INDURUWA"},
  new StationList(){StationCode= "INO", StationID= 103, StationName= "INGURUOYA"},
  new StationList(){StationCode= "INL", StationID= 428, StationName= "INUVIL"},
  new StationList(){StationCode= "JLA", StationID= 107, StationName= "JA-ELA"},
  new StationList(){StationCode= "JFN", StationID= 400, StationName= "JAFFNA"},
  new StationList(){StationCode= "JAP", StationID= 106, StationName= "JAYANTHIPURA"},
  new StationList(){
      StationCode= "KCH", StationID= 338, StationName= "KACHCHERI HALL"},
  new StationList(){
      StationCode= "KDN", StationID= 114, StationName= "KADADASI NAGAR"},
  new StationList(){StationCode= "KMA", StationID= 128, StationName= "KADIGAMUWA"},
  new StationList(){StationCode= "KGW", StationID= 120, StationName= "KADUGANNAWA"},
  new StationList(){StationCode= "KDG", StationID= 113, StationName= "KADUGODA"},
  new StationList(){
      StationCode= "Kahatapitiya", StationID= 480, StationName= "Kahatapitiya"},
  new StationList(){StationCode= "KWE", StationID= 152, StationName= "KAHAWA"},
  new StationList(){StationCode= "KYA", StationID= 154, StationName= "KAKKAPALLIYA"},
  new StationList(){StationCode= "KLW", StationID= 127, StationName= "KALAWEWA"},
  new StationList(){StationCode= "KKH", StationID= 123, StationName= "KALKUDAH"},
  new StationList(){
      StationCode= "KTN", StationID= 147, StationName= "KALUTARA NORTH"},
  new StationList(){
      StationCode= "KTS", StationID= 148, StationName= "KALUTARA SOUTH"},
  new StationList(){
      StationCode= "KMG", StationID= 130, StationName= "KAMBURUGAMUWA"},
  new StationList(){StationCode= "KAN", StationID= 108, StationName= "KANDANA"},
  new StationList(){StationCode= "KGD", StationID= 119, StationName= "KANDEGODA"},
  new StationList(){StationCode= "KDT", StationID= 115, StationName= "KANDY"},
  new StationList(){
      StationCode= "KKS", StationID= 424, StationName= "KANKESANTHURAI"},
  new StationList(){StationCode= "KNI", StationID= 132, StationName= "KANTALE"},
  new StationList(){StationCode= "KAW", StationID= 110, StationName= "KAPUWATTE"},
  new StationList(){StationCode= "KPL", StationID= 139, StationName= "KARADIPUWAL"},
  new StationList(){StationCode= "KTL", StationID= 146, StationName= "KATHALUWA"},
  new StationList(){StationCode= "KAT", StationID= 109, StationName= "KATTUWA"},
  new StationList(){StationCode= "KTG", StationID= 144, StationName= "KATUGASTOTA"},
  new StationList(){
      StationCode= "KTG ROAD",
      StationID= 468,
      StationName= "KATUGASTOTA     ROAD"},
  new StationList(){StationCode= "KUG", StationID= 150, StationName= "KATUGODA"},
  new StationList(){StationCode= "KKD", StationID= 122, StationName= "KATUKURUNDA"},
  new StationList(){
      StationCode= "CAK", StationID= 42, StationName= "KATUNAYAKA AIRPORT"},
  new StationList(){StationCode= "KTK", StationID= 145, StationName= "KATUNAYAKE"},
  new StationList(){StationCode= "KEN", StationID= 117, StationName= "KEENAWALA"},
  new StationList(){StationCode= "KRA", StationID= 141, StationName= "KEKIRAWA"},
  new StationList(){StationCode= "KLA", StationID= 124, StationName= "KELANIYA"},
  new StationList(){StationCode= "KOC", StationID= 333, StationName= "KILINOCHCHI"},
  new StationList(){StationCode= "KNM", StationID= 133, StationName= "KINIGAMA"},
  new StationList(){StationCode= "KRW", StationID= 447, StationName= "KIRINDIWELA"},
  new StationList(){StationCode= "KPE", StationID= 138, StationName= "KIRULAPANA"},
  new StationList(){StationCode= "KEL", StationID= 116, StationName= "KITAL ELLE"},
  new StationList(){StationCode= "KCH", StationID= 111, StationName= "KOCHCHIKADE"},
  new StationList(){StationCode= "KKM", StationID= 397, StationName= "KODIKAMAM"},
  new StationList(){StationCode= "KOG", StationID= 134, StationName= "KOGGALA"},
  new StationList(){
      StationCode= "KOM", StationID= 474, StationName= "KOHOMBILIWALA"},
  new StationList(){StationCode= "KKV", StationID= 429, StationName= "KOKUVIL"},
  new StationList(){StationCode= "KLP", StationID= 126, StationName= "KOLLUPITIYA"},
  new StationList(){StationCode= "KLN", StationID= 453, StationName= "KOLONNAWA"},
  new StationList(){StationCode= "KLN", StationID= 125, StationName= "KOLONNAWA"},
  new StationList(){
      StationCode= "KPN", StationID= 140, StationName= "KOMPANNAVEDIYA"},
  new StationList(){StationCode= "KDV", StationID= 422, StationName= "KONDAVIL"},
  new StationList(){StationCode= "KON", StationID= 135, StationName= "KONWEWA"},
  new StationList(){StationCode= "KOR", StationID= 136, StationName= "KORALAWELLA"},
  new StationList(){StationCode= "KSG", StationID= 143, StationName= "KOSGAMA"},
  new StationList(){StationCode= "KDA", StationID= 112, StationName= "KOSGODA"},
  new StationList(){StationCode= "KHA", StationID= 121, StationName= "KOSHINNA"},
  new StationList(){StationCode= "KGA", StationID= 118, StationName= "KOTAGALA"},
  new StationList(){StationCode= "KOT", StationID= 137, StationName= "KOTTAWA"},
  new StationList(){StationCode= "KWW", StationID= 153, StationName= "KUDA WAWA"},
  new StationList(){StationCode= "KUD", StationID= 149, StationName= "KUDAHAKAPOLA"},
  new StationList(){StationCode= "KMK", StationID= 131, StationName= "KUMARAKANDA"},
  new StationList(){StationCode= "KMB", StationID= 129, StationName= "KUMBALGAMA"},
  new StationList(){
      StationCode= "Karahanhenagama",
      StationID= 408,
      StationName= "KURAHANHENAGAMA"},
  new StationList(){StationCode= "KUR", StationID= 151, StationName= "KURANA"},
  new StationList(){StationCode= "KRN", StationID= 142, StationName= "KURUNEGALA"},
  new StationList(){StationCode= "LYA", StationID= 158, StationName= "LAKSAUYANA"},
  new StationList(){
      StationCode= "LGM", StationID= 155, StationName= "LIYANAGEMULLA"},
  new StationList(){
      StationCode= "LIYANWALA", StationID= 334, StationName= "LIYANWALA"},
  new StationList(){StationCode= "LNA", StationID= 156, StationName= "LUNAWA"},
  new StationList(){StationCode= "LWL", StationID= 157, StationName= "LUNUWILA"},
  new StationList(){StationCode= "MPA", StationID= 181, StationName= "MADAMPAGAMA"},
  new StationList(){StationCode= "MDP", StationID= 161, StationName= "MADAMPE"},
  new StationList(){StationCode= "MRD", StationID= 372, StationName= "MADHU ROAD"},
  new StationList(){
      StationCode= "MKI", StationID= 174, StationName= "MADURANKULIYA"},
  new StationList(){
      StationCode= "MAGALEGODA", StationID= 472, StationName= "Magalegoda"},
  new StationList(){StationCode= "MGG", StationID= 393, StationName= "MAGALEGODA"},
  new StationList(){StationCode= "MGN", StationID= 167, StationName= "MAGGONA"},
  new StationList(){StationCode= "MGG", StationID= 452, StationName= "MAGULEGODA"},
  new StationList(){StationCode= "MYA", StationID= 190, StationName= "MAHAIYAWA"},
  new StationList(){StationCode= "MAG", StationID= 159, StationName= "MAHARAGAMA"},
  new StationList(){StationCode= "MHO", StationID= 170, StationName= "MAHO"},
  new StationList(){StationCode= "MPL", StationID= 182, StationName= "MALAPALLE"},
  new StationList(){StationCode= "MAL", StationID= 427, StationName= "MALLAKAM"},
  new StationList(){StationCode= "MPT", StationID= 183, StationName= "MANAMPITIYA"},
  new StationList(){StationCode= "MGE", StationID= 165, StationName= "MANGALAELIYA"},
  new StationList(){StationCode= "MKM", StationID= 331, StationName= "MANKULAM"},
  new StationList(){StationCode= "MAN", StationID= 434, StationName= "MANNAR"},
  new StationList(){StationCode= "MNG", StationID= 179, StationName= "MANUWANGAMA"},
  new StationList(){StationCode= "MDA", StationID= 160, StationName= "MARADANA"},
  new StationList(){StationCode= "MRK", StationID= 462, StationName= "MARAKONA"},
  new StationList(){StationCode= "MRL", StationID= 454, StationName= "MARALUWEWA"},
  new StationList(){StationCode= "MTL", StationID= 186, StationName= "MATALE"},
  new StationList(){StationCode= "MTR", StationID= 187, StationName= "MATARA"},
  new StationList(){StationCode= "MTM", StationID= 432, StationName= "MATHOTTAM"},
  new StationList(){StationCode= "MWD", StationID= 466, StationName= "MAVILMADA"},
  new StationList(){StationCode= "MVT", StationID= 425, StationName= "MAVITTAPURAM"},
  new StationList(){StationCode= "MEM", StationID= 163, StationName= "MEDAGAMA"},
  new StationList(){
      StationCode= "MWH", StationID= 189, StationName= "MEDAWACHCHIYA"},
  new StationList(){
      StationCode= "MEDDEGAMA", StationID= 421, StationName= "MEDDEGAMA"},
  new StationList(){StationCode= "MGN", StationID= 464, StationName= "MEEGAMMANA"},
  new StationList(){StationCode= "MGD", StationID= 164, StationName= "MEEGODA"},
  new StationList(){StationCode= "MES", StationID= 403, StationName= "MEESALAI"},
  new StationList(){StationCode= "MWA", StationID= 188, StationName= "MHA INDURUWA"},
  new StationList(){StationCode= "MED", StationID= 162, StationName= "MIDIGAMA"},
  new StationList(){StationCode= "MHN", StationID= 169, StationName= "MIHINTALE"},
  new StationList(){
      StationCode= "MHJ", StationID= 168, StationName= "MIHINTALE JUNCTION"},
  new StationList(){StationCode= "MIY", StationID= 173, StationName= "MINNERIYA"},
  new StationList(){StationCode= "MIR", StationID= 171, StationName= "MIRIGAMA"},
  new StationList(){
      StationCode= "MIRIHANPITIGAMA",
      StationID= 409,
      StationName= "MIRIHANPITIGAMA"},
  new StationList(){StationCode= "MIS", StationID= 172, StationName= "MIRISSA"},
  new StationList(){
      StationCode= "Miriswatte", StationID= 443, StationName= "MIRISWATTA"},
  new StationList(){StationCode= "MSL", StationID= 402, StationName= "MIRUSUVIL"},
  new StationList(){StationCode= "MLP", StationID= 177, StationName= "MOLLIPATANA"},
  new StationList(){
      StationCode= "MLG", StationID= 176, StationName= "MORAGOLLAGAMA"},
  new StationList(){StationCode= "MKP", StationID= 175, StationName= "MORAKELE"},
  new StationList(){StationCode= "MRT", StationID= 184, StationName= "MORATUWA"},
  new StationList(){
      StationCode= "MLV", StationID= 439, StationName= "MOUNT LAVINIA"},
  new StationList(){StationCode= "MNL", StationID= 180, StationName= "MUNDAL"},
  new StationList(){StationCode= "MRK", StationID= 332, StationName= "MURIKANDY"},
  new StationList(){StationCode= "MUK", StationID= 431, StationName= "MURUNKAN"},
  new StationList(){
      StationCode= "MTG", StationID= 185, StationName= "MUTHTHETTUGALA"},
  new StationList(){StationCode= "NAG", StationID= 191, StationName= "NAGOLLAGAMA"},
  new StationList(){StationCode= "NLY", StationID= 196, StationName= "NAILIYA"},
  new StationList(){StationCode= "NOA", StationID= 197, StationName= "NANUOYA"},
  new StationList(){StationCode= "NHP", StationID= 195, StationName= "NARAHENPITA"},
  new StationList(){StationCode= "NAT", StationID= 192, StationName= "NATTANDIYA"},
  new StationList(){StationCode= "NVT", StationID= 399, StationName= "NAVATKULI"},
  new StationList(){StationCode= "NVP", StationID= 201, StationName= "NAWALAPITIYA"},
  new StationList(){StationCode= "NWN", StationID= 202, StationName= "NAWINNA"},
  new StationList(){StationCode= "NGM", StationID= 194, StationName= "NEGAMA"},
  new StationList(){StationCode= "NGB", StationID= 193, StationName= "NEGOMBO"},
  new StationList(){
      StationCode= "NELUMPATHGAMA",
      StationID= 415,
      StationName= "NELUMPATHGAMA"},
  new StationList(){StationCode= "NPK", StationID= 199, StationName= "NELUMPOKUNA"},
  new StationList(){StationCode= "NYK", StationID= 370, StationName= "NERIYAKULAM"},
  new StationList(){StationCode= "NOR", StationID= 198, StationName= "NOORANAGAR"},
  new StationList(){StationCode= "NUG", StationID= 200, StationName= "NUGEGODA"},
  new StationList(){StationCode= "OHA", StationID= 203, StationName= "OHIYA"},
  new StationList(){StationCode= "OMT", StationID= 204, StationName= "OMANTHAI"},
  new StationList(){StationCode= "PDK", StationID= 208, StationName= "PADUKKA"},
  new StationList(){
      StationCode= "PAHALAWARDHANA",
      StationID= 420,
      StationName= "PAHALAWARDHANA"},
  new StationList(){StationCode= "PVI", StationID= 238, StationName= "PALAVI"},
  new StationList(){StationCode= "PAL", StationID= 396, StationName= "PALLAI"},
  new StationList(){
      StationCode= "PALLE TALAWINNA",
      StationID= 465,
      StationName= "PALLE TALAVINNA"},
  new StationList(){StationCode= "PLL", StationID= 219, StationName= "PALLEWALA"},
  new StationList(){StationCode= "PUW", StationID= 237, StationName= "PALUGASWEWA"},
  new StationList(){StationCode= "PND", StationID= 223, StationName= "PANADURA"},
  new StationList(){StationCode= "PNG", StationID= 224, StationName= "PANAGODA"},
  new StationList(){StationCode= "PNL", StationID= 226, StationName= "PANALEEYA"},
  new StationList(){StationCode= "PRW", StationID= 233, StationName= "PANGIRIWATTA"},
  new StationList(){StationCode= "PAN", StationID= 205, StationName= "PANNIPITIYA"},
  new StationList(){StationCode= "PKU", StationID= 216, StationName= "PARAKUMPURA"},
  new StationList(){StationCode= "PRN", StationID= 394, StationName= "PARANTHAN"},
  new StationList(){
      StationCode= "PHW", StationID= 213, StationName= "PARASANGAHAWEWA"},
  new StationList(){StationCode= "PGD", StationID= 209, StationName= "PATAGAMGODA"},
  new StationList(){StationCode= "PTP", StationID= 236, StationName= "PATHANPHA"},
  new StationList(){StationCode= "PPL", StationID= 230, StationName= "PATTIPOLA"},
  new StationList(){
      StationCode= "PGN", StationID= 211, StationName= "PAYAGALA NORTH"},
  new StationList(){
      StationCode= "PGS", StationID= 212, StationName= "PAYAGALA SOUTH"},
  new StationList(){StationCode= "PRP", StationID= 232, StationName= "PEMROSE"},
  new StationList(){StationCode= "PDA", StationID= 207, StationName= "PERADENIYA"},
  new StationList(){StationCode= "PKP", StationID= 459, StationName= "PERAKUMPURA"},
  new StationList(){StationCode= "PRL", StationID= 231, StationName= "PERALANDA"},
  new StationList(){
      StationCode= "PNV", StationID= 227, StationName= "PERIYANAGAVILLU"},
  new StationList(){StationCode= "PES", StationID= 436, StationName= "PESALAI"},
  new StationList(){StationCode= "PLD", StationID= 217, StationName= "PILIDUWA"},
  new StationList(){StationCode= "PLT", StationID= 222, StationName= "PILIMATALAWA"},
  new StationList(){
      StationCode= "PINNAGOLLA", StationID= 416, StationName= "PINNAGOLLA"},
  new StationList(){StationCode= "PNW", StationID= 228, StationName= "PINNAWALA"},
  new StationList(){StationCode= "PIN", StationID= 214, StationName= "PINWATTE"},
  new StationList(){StationCode= "PGM", StationID= 210, StationName= "PIYADIGAMA"},
  new StationList(){StationCode= "PYA", StationID= 240, StationName= "PIYAGAMA"},
  new StationList(){
      StationCode= "Polgaha Anga", StationID= 477, StationName= "Polgaha Anga"},
  new StationList(){StationCode= "PLG", StationID= 218, StationName= "POLGAHAWELA"},
  new StationList(){StationCode= "PLN", StationID= 220, StationName= "POLONNARUWA"},
  new StationList(){
      StationCode= "PLR", StationID= 221, StationName= "POLWATHUMODARA"},
  new StationList(){StationCode= "PON", StationID= 229, StationName= "POONEWA"},
  new StationList(){
      StationCode= "PORAPOLA", StationID= 419, StationName= "PORAPOLA"},
  new StationList(){
      StationCode= "PORAPOLA JUNC.",
      StationID= 418,
      StationName= "PORAPOLA JUNC."},
  new StationList(){StationCode= "PTA", StationID= 234, StationName= "POTUHERA"},
  new StationList(){
      StationCode= "PCK", StationID= 206, StationName= "PULACHCHIKULAM"},
  new StationList(){StationCode= "PKM", StationID= 330, StationName= "PULIYANKULAM"},
  new StationList(){StationCode= "PNI", StationID= 225, StationName= "PUNANI"},
  new StationList(){StationCode= "PNK", StationID= 406, StationName= "PUNKANKULAM"},
  new StationList(){StationCode= "PTM", StationID= 235, StationName= "PUTTALAM"},
  new StationList(){StationCode= "PWP", StationID= 445, StationName= "PUWAKPITIYA"},
  new StationList(){
      StationCode= "PWP Town", StationID= 446, StationName= "PUWAKPITIYA TOWN"},
  new StationList(){StationCode= "RDL", StationID= 243, StationName= "RADELLA"},
  new StationList(){StationCode= "RGM", StationID= 246, StationName= "RAGAMA"},
  new StationList(){StationCode= "RBK", StationID= 241, StationName= "RAMBUKKANA"},
  new StationList(){
      StationCode= "RMA", StationID= 247, StationName= "RANAMUGGAMUWA"},
  new StationList(){StationCode= "RGA", StationID= 245, StationName= "RANDENIGAMA"},
  new StationList(){StationCode= "RTG", StationID= 249, StationName= "RATHGAMA"},
  new StationList(){StationCode= "RML", StationID= 248, StationName= "RATMALANA"},
  new StationList(){StationCode= "RDL", StationID= 244, StationName= "REDEETHENNA"},
  new StationList(){
      StationCode= "RCH", StationID= 242, StationName= "RICHMOND HILL"},
  new StationList(){StationCode= "RZL", StationID= 250, StationName= "ROSELLA"},
  new StationList(){StationCode= "SAL", StationID= 251, StationName= "SALIYAPURA"},
  new StationList(){StationCode= "SAK", StationID= 404, StationName= "SANKATHANAI"},
  new StationList(){
      StationCode= "SUA", StationID= 257, StationName= "SARASAVIUYANA"},
  new StationList(){StationCode= "SWR", StationID= 259, StationName= "SAWARANA"},
  new StationList(){
      StationCode= "SCR", StationID= 252, StationName= "SECRETARTAT HALT"},
  new StationList(){StationCode= "SED", StationID= 253, StationName= "SEEDUWA"},
  new StationList(){StationCode= "SMA", StationID= 255, StationName= "SEENIGAMA"},
  new StationList(){StationCode= "SGM", StationID= 254, StationName= "SENARATHGAMA"},
  new StationList(){StationCode= "SVP", StationID= 258, StationName= "SEVANAPITIYA"},
  new StationList(){
      StationCode= "SLM", StationID= 339, StationName= "SIYABALANGAMUWA"},
  new StationList(){
      StationCode= "SYA", StationID= 260, StationName= "SIYALANGAMUWA"},
  new StationList(){
      StationCode= "SRP", StationID= 256, StationName= "SRAWASTHIPURA"},
  new StationList(){StationCode= "TLM", StationID= 437, StationName= "TALAIMANNAR"},
  new StationList(){
      StationCode= "TMP", StationID= 438, StationName= "TALAIMANNAR PIER"},
  new StationList(){StationCode= "TLA", StationID= 270, StationName= "TALAWA"},
  new StationList(){StationCode= "TKL", StationID= 269, StationName= "TALAWAKELE"},
  new StationList(){
      StationCode= "TWG", StationID= 276, StationName= "TALAWATTEGEDARA"},
  new StationList(){StationCode= "TWO", StationID= 461, StationName= "TAWALANOYA"},
  new StationList(){StationCode= "TPI", StationID= 426, StationName= "TELLIPALLAI"},
  new StationList(){StationCode= "TWT", StationID= 277, StationName= "TELWATTE"},
  new StationList(){StationCode= "TBL", StationID= 262, StationName= "TEMBLIGALA"},
  new StationList(){
      StationCode= "TPH", StationID= 405, StationName= "THACHANTHOPPU"},
  new StationList(){StationCode= "TLP", StationID= 271, StationName= "THALPE"},
  new StationList(){
      StationCode= "THAMBAGALLA", StationID= 414, StationName= "THAMBAGALLA"},
  new StationList(){
      StationCode= "TBM", StationID= 263, StationName= "THAMBUTTEGAMA"},
  new StationList(){
      StationCode= "TAN", StationID= 450, StationName= "THAMPALAKAMAM"},
  new StationList(){StationCode= "TDK", StationID= 265, StationName= "THANDIKULAM"},
  new StationList(){
      StationCode= "TVM", StationID= 433, StationName= "THIIRUKETHEESWARAM"},
  new StationList(){StationCode= "TDY", StationID= 267, StationName= "THILLADIYA"},
  new StationList(){StationCode= "TNA", StationID= 272, StationName= "THIRANAGAMA"},
  new StationList(){StationCode= "TVD", StationID= 435, StationName= "THODDAVELI"},
  new StationList(){
      StationCode= "THURULIYAGAMA",
      StationID= 455,
      StationName= "Thuruliyagama"},
  new StationList(){
      StationCode= "TIM", StationID= 268, StationName= "TIMBIRIYAGEDARA"},
  new StationList(){StationCode= "TSM", StationID= 274, StationName= "TISMALPOLA"},
  new StationList(){
      StationCode= "TRH", StationID= 273, StationName= "TRAIN HALT 01"},
  new StationList(){StationCode= "TCO", StationID= 264, StationName= "TRINCOMALEE"},
  new StationList(){StationCode= "TUD", StationID= 275, StationName= "TUDELLA"},
  new StationList(){StationCode= "TDR", StationID= 266, StationName= "TUMMODARA"},
  new StationList(){StationCode= "UDL", StationID= 278, StationName= "UDATALAWINNA"},
  new StationList(){StationCode= "UWL", StationID= 285, StationName= "UDATHTHAWALA"},
  new StationList(){StationCode= "UHM", StationID= 281, StationName= "UDHAMULLA"},
  new StationList(){
      StationCode= "UDUGODAGAMA", StationID= 413, StationName= "UDUGODAGAMA"},
  new StationList(){StationCode= "UDW", StationID= 279, StationName= "UDUWARA"},
  new StationList(){StationCode= "UGL", StationID= 280, StationName= "UGGALLA"},
  new StationList(){StationCode= "UKL", StationID= 282, StationName= "UKUWELA"},
  new StationList(){StationCode= "ULP", StationID= 283, StationName= "ULAPANE"},
  new StationList(){StationCode= "UNW", StationID= 284, StationName= "UNAWATUNA"},
  new StationList(){
      StationCode= "URW", StationID= 451, StationName= "Urugodawattha"},
  new StationList(){
      StationCode= "UYANGALLA", StationID= 412, StationName= "UYANGALLA"},
  new StationList(){StationCode= "VCH", StationID= 286, StationName= "VALACHCHENEI"},
  new StationList(){
      StationCode= "VML", StationID= 288, StationName= "VANDARAMULLAI"},
  new StationList(){StationCode= "VNA", StationID= 289, StationName= "VAVUNIYA"},
  new StationList(){StationCode= "VGD", StationID= 287, StationName= "VEYANGODA"},
  new StationList(){
      StationCode= "WLP", StationID= 340, StationName= "VIRALMURIPPUWA"},
  new StationList(){StationCode= "WDA", StationID= 292, StationName= "WADDUWA"},
  new StationList(){StationCode= "WGG", StationID= 295, StationName= "WAGA"},
  new StationList(){StationCode= "WKL", StationID= 299, StationName= "WAIKKALA"},
  new StationList(){StationCode= "WHP", StationID= 296, StationName= "WALAHAPITIYA"},
  new StationList(){
      StationCode= "WALASWEWA", StationID= 407, StationName= "WALASWEWA"},
  new StationList(){StationCode= "WLG", StationID= 301, StationName= "WALGAMA"},
  new StationList(){StationCode= "WPA", StationID= 303, StationName= "WALPOLA"},
  new StationList(){StationCode= "WSL", StationID= 306, StationName= "WANAWASALA"},
  new StationList(){StationCode= "WRW", StationID= 305, StationName= "WANDURAWA"},
  new StationList(){StationCode= "WTG", StationID= 308, StationName= "WATAGODA"},
  new StationList(){StationCode= "WAP", StationID= 336, StationName= "WATARAKA"},
  new StationList(){StationCode= "WLA", StationID= 300, StationName= "WATAWALA"},
  new StationList(){StationCode= "WGA", StationID= 294, StationName= "WATTEGAMA"},
  new StationList(){
      StationCode= "Weligalla", StationID= 478, StationName= "Weligalla"},
  new StationList(){StationCode= "WLM", StationID= 302, StationName= "WELIGAMA"},
  new StationList(){StationCode= "WKD", StationID= 298, StationName= "WELIKANDA"},
  new StationList(){StationCode= "WEL", StationID= 293, StationName= "WELLAWA"},
  new StationList(){StationCode= "WTE", StationID= 307, StationName= "WELLAWATTA"},
  new StationList(){
      StationCode= "WERAGALA", StationID= 411, StationName= "WERAGALA"},
  new StationList(){
      StationCode= "WRD", StationID= 304, StationName= "WIJAYARAJADAHANA"},
  new StationList(){StationCode= "WWT", StationID= 309, StationName= "WILWATTE"},
  new StationList(){StationCode= "WKA", StationID= 297, StationName= "WLAKUBURA"},
  new StationList(){StationCode= "YGD", StationID= 473, StationName= "YAGODA"},
  new StationList(){StationCode= "YGD", StationID= 387, StationName= "YAGODA"},
  new StationList(){StationCode= "YPW", StationID= 315, StationName= "YAPAHUWA"},
  new StationList(){StationCode= "YGM", StationID= 313, StationName= "YATAGAMA"},
  new StationList(){StationCode= "YWR", StationID= 463, StationName= "YATAWARA"},
  new StationList(){StationCode= "YTR", StationID= 311, StationName= "YATIRAWANA"},
  new StationList(){StationCode= "YTG", StationID= 316, StationName= "YATTALGODA"},
        };
    }
}